<a href="https://colab.research.google.com/github/Ananya-AJ/CMPE255-SafeDose/blob/main/Models/casetype_prediction/Casetype_RandomClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
casetype_train = pd.read_csv('/content/drive/Shareddrives/CMPE255/PCA/encoded_pca_target_casetype_train.csv')
casetype_test = pd.read_csv('/content/drive/Shareddrives/CMPE255/PCA/encoded_pca_target_casetype_test.csv')

In [ ]:
casetype_test.isna().sum()

In [ ]:
casetype_xtrain = casetype_train.iloc[:,1:]

In [ ]:
casetype_xtrain.isna().sum()

In [ ]:
casetype_ytrain = casetype_test.iloc[:,1:]

In [ ]:
casetype_xtrain_ = casetype_xtrain.drop(['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8'],axis=1)
casetype_ytrain_ = casetype_xtrain[['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8']]

In [ ]:
casetype_ytrain_['target'] = pd.get_dummies(casetype_ytrain_[['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8']]).idxmax(1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
casetype_ytrain_['target'] =casetype_ytrain_['target'].map({'CASETYPE_1':1,'CASETYPE_2':2,'CASETYPE_3':3,'CASETYPE_4':4,'CASETYPE_5':5,'CASETYPE_6':6,'CASETYPE_7':7,'CASETYPE_8':8})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
casetype_ytrain_ = casetype_ytrain_.drop(['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8'],axis=1)
casetype_ytrain_.head()

target
0       8
1       8
2       8
3       4
4       5

In [ ]:
casetype_xtest = casetype_test.iloc[:,1:]

In [ ]:
casetype_ytest = casetype_test.iloc[:,1:]

In [ ]:
casetype_xtest_ = casetype_xtest.drop(['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8'],axis=1)
casetype_ytest_ = casetype_ytest[['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8']]

In [ ]:
casetype_ytest_['target'] = pd.get_dummies(casetype_ytest_[['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8']]).idxmax(1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
casetype_ytest_['target'] =casetype_ytest_['target'].map({'CASETYPE_1':1,'CASETYPE_2':2,'CASETYPE_3':3,'CASETYPE_4':4,'CASETYPE_5':5,'CASETYPE_6':6,'CASETYPE_7':7,'CASETYPE_8':8})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
casetype_ytest_ = casetype_ytest_.drop(['CASETYPE_1','CASETYPE_2',	'CASETYPE_3',	'CASETYPE_4',	'CASETYPE_5',	'CASETYPE_6',	'CASETYPE_7',	'CASETYPE_8'],axis=1)
casetype_ytest_.head()

target
0       8
1       4
2       3
3       4
4       4

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [ ]:
f1_score_train = []
f1_score_test = []
accuracy_s = []

In [ ]:
n_estimators = [10,20,50,100]
for i in n_estimators:
  print(i)
  rf = RandomForestClassifier(n_estimators = i, random_state = 42)
  rf.fit(casetype_xtrain_, casetype_ytrain_)
  predictions = rf.predict(casetype_xtest_)
  #confusion_matrix(y_test, prediction)
  print(type(predictions))
  accuracy = accuracy_score(casetype_ytest_, np.array(predictions))
  print(confusion_matrix(casetype_ytest_, predictions))
  f1_score_ = f1_score(casetype_ytest_,predictions,average='macro')
  f1_score_train.append(f1_score_)
  accuracy_s.append(accuracy)

10


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


<class 'numpy.ndarray'>
[[  742   127    14   560     1     0     2   132]
 [  130  1364     5   179     0     0     1  1006]
 [    2     2  1446     0     0     0     0     0]
 [  286   100     0 16822     0     0    49     6]
 [    0     0     0    15  2424     4     0   940]
 [    1     1     0     0     8    45     0    78]
 [   27     7     0   491     0     0    92    15]
 [   26   448     0     5  1083    41     1 15062]]
20


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


<class 'numpy.ndarray'>
[[  732   132    14   562     1     0     3   134]
 [  110  1365     5   176     0     0     1  1028]
 [    2     1  1447     0     0     0     0     0]
 [  244    84     0 16886     1     0    43     5]
 [    1     0     0     9  2425     2     0   946]
 [    1     1     0     0     9    42     0    80]
 [   22     5     0   491     0     0    98    16]
 [   18   377     0     2  1014    34     0 15221]]
50


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


<class 'numpy.ndarray'>
[[  717   129    14   580     0     0     0   138]
 [   94  1364     5   188     0     0     0  1034]
 [    2     1  1447     0     0     0     0     0]
 [  198    68     0 16949     0     0    40     8]
 [    0     0     0     5  2416     4     0   958]
 [    1     0     0     0     9    41     0    82]
 [   23     3     0   487     0     0   103    16]
 [   17   348     0     1   942    30     0 15328]]
100


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


<class 'numpy.ndarray'>
[[  707   136    14   583     0     0     0   138]
 [   92  1361     5   182     0     0     0  1045]
 [    2     1  1447     0     0     0     0     0]
 [  188    67     0 16963     0     0    39     6]
 [    0     0     0     5  2432     2     0   944]
 [    1     0     0     0     8    40     0    84]
 [   23     4     0   487     0     0   102    16]
 [   16   345     0     1   928    28     0 15348]]


In [ ]:
print(f1_score_train)
print(accuracy_s)


[0.6604522221132332, 0.6659324569122684, 0.669760221689363, 0.669699431606706]
[0.8677095227220827, 0.872710664535282, 0.8761132678693766, 0.876912537108929]


In [ ]:
accuracy_trainpreds = []
f1_trainpreds = []

In [ ]:
n_estimators = [10,20,50]
for i in n_estimators:
  print(i)
  rf = RandomForestClassifier(n_estimators = i, random_state = 42)
  rf.fit(casetype_xtrain_, casetype_ytrain_)
  predictions = rf.predict(casetype_xtrain_)
  confusion_matrix(casetype_ytrain_, predictions)
  accuracy = accuracy_score(casetype_ytrain_, np.array(predictions))
  f1_score_ = f1_score(casetype_ytrain_,predictions,average='macro')
  f1_trainpreds.append(f1_score_)
  accuracy_trainpreds.append(accuracy)

10


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


20


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


50


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


In [ ]:
print(f1_trainpreds)
print(accuracy_trainpreds)

[0.9456216082293065, 0.9568592166054335, 0.9616230139434686]
[0.9730189540991094, 0.9769467915049098, 0.9786138387759763]
